CIRCUITPY_WIFI_SSID="network"
CIRCUITPY_WIFI_PASSWORD="password"

CIRCUITPY_WEB_API_PORT=80
CIRCUITPY_WEB_API_PASSWORD="picopad"

GOLEMIO_API_KEY=" Generate your API key at https://api.golemio.cz/api-keys/auth/sign-up "
STOP_GTFS_ID="U717Z1P"
STOP_NAME="Muzeum"
